# Generated by Django 6.1.1 on 2026-10-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_location_stocklevel_stockmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='sender',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
